import { spawnSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const CLI = join(process.cwd(), "packages", "recon", "src", "cli.ts");

function runCli(args: string[]) {
  return spawnSync(process.execPath, [CLI, ...args], {
    cwd: process.cwd(),
    encoding: "utf8",
    shell: false,
  });
}

describe("CLI --fail-on", () => {
  it("exits 1 after writing JSON when findings meet the threshold", () => {
    const res = runCli(["scan", "--mode", "demo", "--json", "--fail-on", "critical"]);

    expect(res.status).toBe(1);
    expect(res.stdout).toContain('"findings"');
    expect(res.stderr).toBe("");
  });

  it("exits 0 when there are no findings at or above the threshold", () => {
    const res = runCli(["scan", "--mode", "static", "--json", "--fail-on", "low"]);

    expect(res.status).toBe(0);
    expect(res.stdout).toContain('"findings": []');
  });

  it("rejects an invalid threshold", () => {
    const res = runCli(["scan", "--mode", "demo", "--json", "--fail-on", "blocker"]);

    expect(res.status).toBe(2);
    expect(res.stdout).toContain('"findings"');
    expect(res.stderr).toContain("--fail-on must be one of");
  });

  it("renders project intent context from --intent", () => {
    const dir = mkdtempSync(join(tmpdir(), "recon-intent-"));
    const intent = join(dir, "intent.md");
    writeFileSync(intent, "Keep telegram disabled unless a user reconnects it.");

    const res = runCli(["scan", "--mode", "demo", "--intent", intent]);

    expect(res.status).toBe(0);
    expect(res.stdout).toContain("## Project intent");
    expect(res.stdout).toContain("Keep telegram disabled");
  });

  it("runs portfolio mode as evidence fan-out", () => {
    const res = runCli(["scan", "--mode", "portfolio", "--dir", "corpus", "--json"]);

    expect(res.status).toBe(0);
    expect(res.stdout).toContain('"mode": "evidence"');
    expect(res.stdout).toContain("central-genial");
  });

  it("renders corpus mode over the evidence directory", () => {
    const res = runCli(["scan", "--mode", "corpus", "--dir", "corpus"]);

    expect(res.status).toBe(0);
    expect(res.stdout).toContain("# Lovable Portfolio Recon Report");
    expect(res.stdout).toContain("**Projects:** 19");
    expect(res.stdout).toContain("Generated by `recon scan --mode corpus`");
  });
});
