import type { Finding, ImportedAction, ReconResult, Resource, Severity } from "./model.ts";

const SEV_BADGE: Record<Severity, string> = {
  critical: "🔴 Critical",
  high: "🟠 High",
  medium: "🟡 Medium",
  low: "⚪ Low",
};

export function renderReport(result: ReconResult): string {
  const { project, resources, findings, score, warnings, assessed } = result;
  const L: string[] = [];

  L.push(`# ${project.name} — Recon Usage Report`);
  L.push("");
  L.push(`**Waste-score:** ${score.wasteScore}/100 · ${score.headline}  `);
  const metaBits = [
    project.supabaseRef ? `ref \`${project.supabaseRef}\`` : null,
    project.stack,
    `mode \`${project.mode}\``,
    project.evidenceGenerated ? `evidence ${project.evidenceGenerated.slice(0, 10)}` : null,
    `scanned ${project.scannedAt.slice(0, 10)}`,
  ].filter(Boolean);
  L.push(`_${metaBits.join(" · ")}_`);
  L.push("");
  if (assessed === false) {
    L.push("> ⚠️ **Incomplete assessment** — this collector is a stub and did not evaluate runtime. Absence of findings is not a clean bill of health.");
    L.push("");
  }
  L.push("---");
  L.push("");

  // Tier 0 — capability matrix
  L.push("## Capability matrix");
  L.push("");
  L.push(renderCapabilityMatrix(resources));
  L.push("");

  // Findings
  L.push("## Findings");
  L.push("");
  if (findings.length === 0) {
    L.push("_No waste findings. Runtime looks clean._");
  } else {
    L.push("| # | Policy | Severity | Conf. | Finding | Est. saved |");
    L.push("|--:|---|---|---|---|---|");
    findings.forEach((f, i) => {
      L.push(`| ${i + 1} | ${f.policy} | ${SEV_BADGE[f.severity]} | ${f.confidence} | ${f.title} | ${f.estCreditsSaved ?? "—"} |`);
    });
    L.push("");
    for (const [i, f] of findings.entries()) {
      L.push(renderFindingDetail(f, i + 1));
    }
  }

  if (result.importedActions.length) {
    L.push("## Imported audit actions");
    L.push("");
    L.push("_Context from the source audit. These actions are not counted in the waste-score._");
    L.push("");
    L.push(renderImportedActions(result.importedActions));
    L.push("");
  }

  // Score breakdown
  L.push("## Waste-score breakdown");
  L.push("");
  if (score.breakdown.length === 0) {
    L.push("_—_");
  } else {
    L.push("| Policy | Findings | Points |");
    L.push("|---|--:|--:|");
    for (const b of score.breakdown) L.push(`| ${b.policy} | ${b.count} | ${b.points} |`);
  }
  L.push("");

  if (warnings.length) {
    L.push("## Collector warnings");
    L.push("");
    for (const w of warnings) L.push(`- ${w}`);
    L.push("");
  }

  L.push("---");
  L.push("");
  L.push("_Generated by `recon scan` (read-only). Remediation is proposed, never applied — " + "`recon clean --apply` (future) will require `confirmed` findings + review._");
  L.push("");
  return L.join("\n");
}

function renderImportedActions(actions: ImportedAction[]): string {
  const rows = ["| Rank | Policy | Severity | Status | Effort | Action |", "|--:|---|---|---|---|---|"];
  for (const a of actions) {
    rows.push(`| ${a.rank ?? ""} | ${a.policy ?? ""} | ${a.severity ?? ""} | ${a.status ?? ""} | ${a.effort ?? ""} | ${a.action.replace(/\|/g, "\\|")} |`);
  }
  return rows.join("\n");
}

function renderCapabilityMatrix(resources: Resource[]): string {
  const count = (k: string) => resources.filter((r) => r.kind === k).length;
  const project = resources.find((r) => r.kind === "project");
  const attrNum = (k: string) => (typeof project?.attrs[k] === "number" ? (project.attrs[k] as number) : undefined);
  const cloud = resources.find((r) => r.kind === "cloud");
  const ai = resources.find((r) => r.kind === "ai_config");
  const rt = resources.find((r) => r.kind === "realtime");
  const rows: [string, string][] = [
    ["Lovable Cloud (DB)", cloud ? `✅ ${cloud.attrs["status"] ?? "active"}` : "—"],
    ["Lovable AI", ai ? `✅ model \`${ai.attrs["model"] ?? "?"}\`` : "✗ not configured"],
    ["Tables (public)", String(attrNum("tables") ?? count("table"))],
    ["Cron jobs", String(count("cron_job"))],
    ["Edge functions", String(attrNum("edgeFns") ?? count("edge_fn"))],
    ["Storage buckets", String(count("bucket"))],
    ["Realtime", rt ? `✅ ${rt.attrs["tables"] ?? "on"} table(s)` : "✗ off"],
    ["RLS policies seen", String(count("rls_policy"))],
  ];
  return ["| Capability | State |", "|---|---|", ...rows.map(([k, v]) => `| ${k} | ${v} |`)].join("\n");
}

function renderFindingDetail(f: Finding, n: number): string {
  const B: string[] = [];
  B.push(`### ${n}. [${f.policy}] ${f.title}`);
  B.push("");
  B.push(`${SEV_BADGE[f.severity]} · confidence **${f.confidence}**` + (f.driverCat ? ` · driver \`${f.driverCat}\`` : "") + (f.estCreditsSaved ? ` · est. saved **${f.estCreditsSaved}**` : ""));
  B.push("");
  B.push(f.rationale);
  B.push("");
  if (f.evidence.length) {
    B.push("**Evidence**");
    for (const e of f.evidence) {
      B.push(`- _(${e.source})_ ${e.detail}`);
      if (e.snippet) {
        B.push("");
        B.push("  ```");
        for (const line of e.snippet.split("\n")) B.push(`  ${line}`);
        B.push("  ```");
      }
    }
    B.push("");
  }
  if (f.remediation.length) {
    B.push("**Remediation**");
    for (const r of f.remediation) {
      const lang = r.kind === "sql_migration" ? "sql" : r.kind === "lovable_prompt" ? "text" : "";
      B.push(`- ${r.title}  _(${r.kind}${r.applySafe ? ", auto-applicable" : ", review required"})_`);
      B.push("");
      B.push("  ```" + lang);
      for (const line of r.body.split("\n")) B.push(`  ${line}`);
      B.push("  ```");
    }
    B.push("");
  }
  return B.join("\n");
}
